# 本地开发环境 Docker Compose 配置
version: '3.8'

services:
  # Elasticsearch 单节点配置 (轻量级)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: caie-elasticsearch
    environment:
      - node.name=es-node
      - cluster.name=caie-cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"  # 限制内存使用
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - caie-network
    restart: unless-stopped

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: caie-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - caie-network
    restart: unless-stopped

volumes:
  elasticsearch_data:
  redis_data:

networks:
  caie-network:
    driver: bridge